### ISSUE TITLE
Make "Studio" intro animations

### ISSUE THREAD

**Issue by MsBlockCat** [MrBlockCat/Porject-Alpha#4]
You know the ones at the start of games, well we could have them but ASCII ones for each of us

**Comment by frenchfreys** [comment]
Good idea

**Comment by MsBlockCat** [comment]
I added mine! It doesn't have to be super complex as you can see by mine, only like a few seconds, it didn't take a really long time to make and it was kinda fun

**Comment by frenchfreys** [comment]
hmmm

**Comment by frenchfreys** [comment]
Bang it's done gamininggggggg
